# Generated by Django 4.0.1 on 2022-04-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thestart',
            table='THESTART',
        ),
    ]
